"""added a new topic field to stroke mortaility

Revision ID: 2d3f1ef08379
Revises: a9eb197dec04
Create Date: 2026-09-22 13:31:54.705577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3f1ef08379'
down_revision: Union[str, Sequence[str], None] = 'a9eb197dec04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stroke_mortality', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stroke_mortality', 'topic')
    # ### end Alembic commands ###
