"""Remove the age, lower_limit, upper_limit columns

Revision ID: 2dc62166f25a
Revises: bf3592ed54ab
Create Date: 2026-08-12 13:44:02.165053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc62166f25a'
down_revision: Union[str, Sequence[str], None] = 'bf3592ed54ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stroke_mortality', 'lower_limit')
    op.drop_column('stroke_mortality', 'age')
    op.drop_column('stroke_mortality', 'upper_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stroke_mortality', sa.Column('upper_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stroke_mortality', sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stroke_mortality', sa.Column('lower_limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
