"""added dlt columns for both current tables

Revision ID: 6518760e5289
Revises: f8af2395fbb7
Create Date: 2026-08-04 15:24:58.361708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6518760e5289'
down_revision: Union[str, Sequence[str], None] = 'f8af2395fbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diabetes_ind', sa.Column('_dlt_id', sa.String(length=50), nullable=True))
    op.add_column('diabetes_ind', sa.Column('_dlt_load_id', sa.String(length=50), nullable=True))
    op.add_column('stroke_mortality', sa.Column('_dlt_id', sa.String(length=50), nullable=True))
    op.add_column('stroke_mortality', sa.Column('_dlt_load_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stroke_mortality', '_dlt_load_id')
    op.drop_column('stroke_mortality', '_dlt_id')
    op.drop_column('diabetes_ind', '_dlt_load_id')
    op.drop_column('diabetes_ind', '_dlt_id')
    # ### end Alembic commands ###
