"""Added nullable fields to every column in our current tables(diabetes_ind and stroke_mortality)

Revision ID: 6a2ad777dd3a
Revises: 6518760e5289
Create Date: 2026-08-07 13:16:30.482738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a2ad777dd3a'
down_revision: Union[str, Sequence[str], None] = '6518760e5289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_dlt_pipeline_state')
    op.drop_table('_dlt_loads')
    op.drop_table('_dlt_version')
    op.alter_column('diabetes_ind', 'year',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.alter_column('stroke_mortality', 'year',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stroke_mortality', 'year',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.alter_column('diabetes_ind', 'year',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    op.create_table('_dlt_version',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('engine_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schema', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_table('_dlt_loads',
    sa.Column('load_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('schema_version_hash', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('_dlt_pipeline_state',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('engine_version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('pipeline_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('version_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_dlt_load_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('_dlt_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.UniqueConstraint('_dlt_id', name=op.f('_dlt_pipeline_state__dlt_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
