"""Added topic column

Revision ID: a9eb197dec04
Revises: 2dc62166f25a
Create Date: 2026-08-19 14:33:13.057961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9eb197dec04'
down_revision: Union[str, Sequence[str], None] = '2dc62166f25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diabetes_ind', sa.Column('topic', sa.String(), nullable=True))
    op.drop_column('diabetes_ind', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diabetes_ind', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('diabetes_ind', 'topic')
    # ### end Alembic commands ###
