"""Added New new columns to storke_mortality

Revision ID: bf3592ed54ab
Revises: dda5960e1049
Create Date: 2026-08-12 13:07:34.562604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3592ed54ab'
down_revision: Union[str, Sequence[str], None] = 'dda5960e1049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stroke_mortality', sa.Column('icd_class', sa.String(), nullable=True))
    op.add_column('stroke_mortality', sa.Column('value', sa.Float(), nullable=True))
    op.add_column('stroke_mortality', sa.Column('lower_limit', sa.Float(), nullable=True))
    op.add_column('stroke_mortality', sa.Column('upper_limit', sa.Float(), nullable=True))
    op.add_column('stroke_mortality', sa.Column('age', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stroke_mortality', 'age')
    op.drop_column('stroke_mortality', 'upper_limit')
    op.drop_column('stroke_mortality', 'lower_limit')
    op.drop_column('stroke_mortality', 'value')
    op.drop_column('stroke_mortality', 'icd_class')
    # ### end Alembic commands ###
