"""Remove dlt columns

Revision ID: dda5960e1049
Revises: 2e2a873de307
Create Date: 2026-08-11 15:55:45.942192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda5960e1049'
down_revision: Union[str, Sequence[str], None] = '2e2a873de307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diabetes_ind', '_dlt_load_id')
    op.drop_column('diabetes_ind', '_dlt_id')
    op.drop_column('stroke_mortality', '_dlt_load_id')
    op.drop_column('stroke_mortality', '_dlt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stroke_mortality', sa.Column('_dlt_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('stroke_mortality', sa.Column('_dlt_load_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('diabetes_ind', sa.Column('_dlt_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('diabetes_ind', sa.Column('_dlt_load_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
