"""Renamed estimates and se_estimates to estimate and se_estimate in diabetes_ind

Revision ID: f78c010c4bd6
Revises: 6a2ad777dd3a
Create Date: 2026-08-10 14:40:13.985913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78c010c4bd6'
down_revision: Union[str, Sequence[str], None] = '6a2ad777dd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diabetes_ind', sa.Column('estimate', sa.Float(), nullable=True))
    op.add_column('diabetes_ind', sa.Column('se_estimate', sa.Float(), nullable=True))
    op.drop_column('diabetes_ind', 'estimates')
    op.drop_column('diabetes_ind', 'se_estimates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diabetes_ind', sa.Column('se_estimates', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('diabetes_ind', sa.Column('estimates', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('diabetes_ind', 'se_estimate')
    op.drop_column('diabetes_ind', 'estimate')
    # ### end Alembic commands ###
