"""fixed a typo on diabetes_ind table education column

Revision ID: f8af2395fbb7
Revises: 369d5fd2aee6
Create Date: 2026-08-04 15:20:38.853285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8af2395fbb7'
down_revision: Union[str, Sequence[str], None] = '369d5fd2aee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diabetes_ind', sa.Column('education', sa.String(), nullable=True))
    op.drop_column('diabetes_ind', 'eductaion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diabetes_ind', sa.Column('eductaion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('diabetes_ind', 'education')
    # ### end Alembic commands ###
